name: Generate Web Client

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: "11"
      - run: npm run generate:client:web
      - run: npm run format
      - run: npm run lint
      - id: check-diff
        name: check for changes
        run: |
          if git diff --exit-code; then
            echo "changes_exist=false" >> $GITHUB_OUTPUT
          else
            echo "changes_exist=true" >> $GITHUB_OUTPUT
          fi
      - uses: peter-evans/create-pull-request@v7
        if: steps.check-diff.outputs.changes_exist == 'true'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "feat: update Web Client"
          commit-message: "feat: update web client"
          base: main
          branch: feat/update-web-client
          delete-branch: true
          body: |
            Automatically generated changes by `npm run generate:client:web`
