name: Generate Web Client

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "11"
      - run: npm run update-swagger-web
      - id: check-yaml-diff
        uses: technote-space/get-diff-action@v6
      - run: npm run generate:client:web
      - run: npm run format
      - run: npm run lint
      - id: check-diff
        uses: technote-space/get-diff-action@v6
      - uses: peter-evans/create-pull-request@v5
        if: steps.check-diff.outputs.diff
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "feat: update Web Client"
          commit-message: "feat: update web client"
          base: main
          branch: feat/update-web-client
          delete-branch: true
          body: |
            Automatically generated changes by `npm run generate:client:web`
