name: Publish to npm

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # https://github.com/jdx/mise-action/releases/tag/v4.0.1
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151
      - run: npm ci
      - run: npm run test
      - run: npm publish --access=public
